### ISSUE TITLE
How do I apply two velocity inlet conditions to two different boundaries?

### ISSUE THREAD

**Issue by sidkamat** [ucns3d-team/UCNS3D#57]
Hi.
I am trying to set up a case where I have a liquid jet get introduced in a stream of air. For this, I need two velocity inlet boundaries. The u-freestream in the UCNS3D.DAT applies to only one inlet boundary if I am not wrong. I also looked at the INFLOW function in the flow_operations.f90 module but I am not able to figure out how to assign two different velocity inlet conditions to two different boundaries.

Any help would be greatly appreciated.
Thanks

**Comment by SRkumar97** [comment]
Hi, may I know how you resolved your issue? I'm also stuck in the INFLOW for introducing a velocity profile.
Thanks!

**Comment by sidkamat** [comment]
> Hi, may I know how you resolved your issue? I'm also stuck in the INFLOW for introducing a velocity profile.
> 
> Also, was this thread initiated by you? https://www.cfd-online.com/Forums/fluent-udf/243601-problem-using-flow-variables-inside-macro.html
> 
> Thanks!

Hi,
I did not use two velocity inlet conditions. I got around the problem using a suitable initial condition.

Yes, that thread was initiated by me but that was for a completely different project.
