### ISSUE TITLE
Tutorials and the usage of MRF

### ISSUE THREAD

**Issue by SRkumar97** [ucns3d-team/UCNS3D#66]
Hello!
I have a couple of doubts on the MRF feature of the code. The provided MRF doc https://github.com/ucns3d-team/UCNS3D/blob/master/docs/README_MRF.md
mentions that there are a suite of testcases with the MRF, which can be accessed using the link https://cord.cranfield.ac.uk/

When I open the cord webpage I see a variety of groups and categories.
May I know which category/sub-tree I am supposed to check in the cord website, for accessing these tutorials?

Additionally, can MRF in UCNS3D be used with both purely structured grids?

**Comment by paulostrobel** [comment]
Thanks for your update. I will check the  cases on cord and get back to this soon. In terms of the mesh, it also support structured grid.

**Comment by paulostrobel** [comment]
I just double checked the files and both meshes and results are on the cord repository.  You can access each case repository with the hyperlinks on the MRF doc readme.  An additional repository containing only the tutorial meshes will be provided soon.

**Comment by SRkumar97** [comment]
Thank you very much for the help!
