### ISSUE TITLE
Test simulation issue

### ISSUE THREAD

**Issue by JihoonKimKorea** [ucns3d-team/UCNS3D#88]
Hi,

I am trying to run an example simulation after compilation.

It seems there is an issue with ParMETIS related to MPI segmentation.

I would greatly appreciate it if someone could guide me on how to resolve this issue.

I've attached the error message below.

ucns3d_p will run on 2 MPI tasks.
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
 i read the bleed BC
 RESTARTING           0   0.0000000000000000                0
 ------------------------------------------------------------------------
                        ParMETIS Initiated                               
 ------------------------------------------------------------------------
[kucfd-System:909616] *** An error occurred in MPI_Comm_rank
[kucfd-System:909616] *** reported by process [1937178625,0]
[kucfd-System:909616] *** on communicator MPI_COMM_WORLD
[kucfd-System:909616] *** MPI_ERR_COMM: invalid communicator
[kucfd-System:909616] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[kucfd-System:909616] ***    and potentially your MPI job)
[kucfd-System:909609] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[kucfd-System:909609] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Comment by JihoonKimKorea** [comment]
Thanks for reply Takis,

The operating system is Ubuntu 22.04 and tried compilation from source code, not using docker.
UCNS3D.DAT file is from TEST1 KHI example.
I just exported OMP_NUM_THREADS=2

I would greatly appreciate it if you could provide your comments on it.

**Comment by JihoonKimKorea** [comment]
Here's the error message and files in working directory after getting error.
![image](https://github.com/user-attachments/assets/df7b9777-6170-4f16-a375-16cae16bae0d)

![image](https://github.com/user-attachments/assets/5b392ebd-6278-4e7f-a648-115bd901aea5)

**Comment by TakisCFD** [comment]
I assume that there might be an issue with the parmetis since this is when the code crashes.
Please check the following:
1) If you are running a 2D case do you have the 2D option in the UCNS3D.DAT file?
2) check the chmod of ucns3d_p since the authorisation required message might indicate something related to that?
3) Check what compilers combo you are using (Gnu with OpenMPI/MPICH should work, Intel fortran with Intel MPI should work, GNU with CrayMPI/HPE mpi should work, however when switching with **_intel fortran and openmpi_** or **_gnu fortran with intel mpi_** you might get these issue.

**Comment by JihoonKimKorea** [comment]
1. Yes, I have 2D option in the UCNS3D.DAT file.
2. When I try to run the code on Ubuntu machine, I have chmod -X ./ucns3d_p command in the shell script.
3. I'm using gnu compiler with OpenMPI.

I tried 3d example case as well, but the same error happens.

I'm curious about where the error comes. Is the error from compilation with ParMETIS?

**Comment by dudugang** [comment]
I got the same error with Gnu compiler and OpenMPI
